# lenovo-sw fuxm1 2015-02-12 add for smartpa need include gpio info begain
include $(srctree)/drivers/misc/mediatek/Makefile.custom
# lenovo-sw fuxm1 2015-02-12 add for smartpa need include gpio info begain

obj-$(CONFIG_MTK_SOUND) += AudDrv_NXP.o